football:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('FOOTBALL_DB_HOST', 'localhost') }}"
      port: "{{ env_var('FOOTBALL_DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('FOOTBALL_DB_NAME', 'football') }}"
      user: "{{ env_var('FOOTBALL_DB_USER', 'football') }}"
      password: "{{ env_var('FOOTBALL_DB_PASS', 'football') }}"
      schema: public
      threads: 4
